[custom]
#ruleset=国内网站,clash-classic:https://ghproxy.com/https://raw.githubusercontent.com/Infatuation-Fei/rule/main/Clash/Rule/OtherDirect.yaml
ruleset=Bobby,clash-classic:https://ghproxy.com/https://raw.githubusercontent.com/pdlwf/router-rule/main/Clash/Rule/bobby_customize.yaml
#ruleset=国内直连,clash-classic:https://ghproxy.com/https://raw.githubusercontent.com/pdlwf/router-rule/main/Clash/Rule/bobby_lan.yaml
ruleset=apiopenai,clash-classic:https://ghproxy.com/https://raw.githubusercontent.com/pdlwf/router-rule/main/Clash/Rule/platform-openai.yaml
ruleset=OpenAI,clash-classic:https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml
ruleset=巴姆哈特,clash-classic:https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.yaml
ruleset=Twitter,clash-classic:https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.yaml
ruleset=Telegram,clash-ipcidr:https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt
ruleset=Amazon,clash-classic:https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Amazon/Amazon.yaml
ruleset=Github,clash-classic:https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml
ruleset=PayPal,clash-classic:https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PayPal/PayPal.yaml
ruleset=Nintendo,clash-classic:https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nintendo/Nintendo.yaml
ruleset=Netflix,clash-classic:https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix_Classical.yaml
#ruleset=GDrive,clash-classic:https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleDrive/GoogleDrive.yaml
ruleset=YouTubeMusic,clash-classic:https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTubeMusic/YouTubeMusic.yaml
ruleset=YouTube,clash-classic:https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml
ruleset=GoogleVoice,clash-classic:https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleVoice/GoogleVoice.yaml
ruleset=GoogleFCM,clash-classic:https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.yaml
ruleset=Google,clash-classic:https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml
#ruleset=ITV,clash-classic:https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleTV/AppleTV.yaml
#ruleset=AppleMail,clash-classic:https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleMail/AppleMail.yaml
ruleset=苹果服务,clash-domain:https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple_Domain.yaml
ruleset=微软服务,clash-classic:https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml
ruleset=哔哩哔哩,clash-classic:https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml
ruleset=HoYoGames,clash-classic:https://ghproxy.com/https://raw.githubusercontent.com/Infatuation-Fei/rule/main/Clash/Rule/HoYoGames.yaml
ruleset=游戏平台,clash-classic:https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.yaml
ruleset=国外网站,clash-domain:https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Proxy/Proxy_Domain.yaml
ruleset=国内网站,clash-domain:https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China_Domain.yaml
ruleset=DIRECT,[]GEOIP,LAN
ruleset=国内网站,[]GEOIP,CN
ruleset=漏网之鱼,[]FINAL

custom_proxy_group=手动切换`select`.*
custom_proxy_group=国外网站`select`[]手动切换`[]美国节点`[]新加坡节点`[]香港节点`[]日本节点
custom_proxy_group=国内网站`select`[]DIRECT`[]手动切换`[]美国节点`[]新加坡节点`[]香港节点
#custom_proxy_group=国内直连`select`[]DIRECT`[]美国节点`[]新加坡节点`[]香港节点`[]快速节点
#custom_proxy_group=GDrive`select`[]手动切换`[]美国节点`[]新加坡节点`[]香港节点
custom_proxy_group=Google`select`[]手动切换`[]美国节点`[]新加坡节点`[]香港节点
custom_proxy_group=GoogleVoice`select`[]手动切换`[]美国节点`[]新加坡节点`[]香港节点
custom_proxy_group=YouTube`select`[]手动切换`[]美国节点`[]新加坡节点`[]香港节点`[]快速节点
custom_proxy_group=YouTubeMusic`select`[]手动切换`[]美国节点`[]新加坡节点`[]香港节点
custom_proxy_group=GoogleFCM`select`[]手动切换`[]美国节点`[]新加坡节点`[]香港节点
#custom_proxy_group=ITV`select`[]手动切换`[]美国节点`[]新加坡节点`[]香港节点
#custom_proxy_group=AppleMail`select`[]手动切换`[]美国节点`[]新加坡节点`[]香港节点
custom_proxy_group=苹果服务`select`[]DIRECT`[]美国节点`[]新加坡节点`[]香港节点
custom_proxy_group=Amazon`select`[]手动切换`[]美国节点`[]新加坡节点`[]香港节点
custom_proxy_group=Github`select`[]手动切换`[]美国节点`[]新加坡节点`[]香港节点`[]快速节点
custom_proxy_group=OpenAI`select`[]手动切换`[]美国节点`[]新加坡节点`[]香港节点`[]台湾节点`[]日本节点
custom_proxy_group=巴姆哈特`select`[]手动切换`[]台湾节点`[]新加坡节点`[]香港节点
custom_proxy_group=Twitter`select`[]手动切换`[]美国节点`[]新加坡节点`[]香港节点`[]快速节点
custom_proxy_group=Telegram`select`[]手动切换`[]美国节点`[]新加坡节点`[]香港节点`[]快速节点
custom_proxy_group=PayPal`select`[]美国节点`[]新加坡节点`[]香港节点
custom_proxy_group=Netflix`select`[]手动切换`[]美国节点`[]新加坡节点`[]香港节点
custom_proxy_group=Nintendo`select`[]手动切换`[]美国节点`[]新加坡节点`[]香港节点
custom_proxy_group=微软服务`select`[]手动切换`[]美国节点`[]新加坡节点`[]香港节点`[]DIRECT
custom_proxy_group=哔哩哔哩`select`[]DIRECT`[]手动切换`[]美国节点`[]新加坡节点`[]香港节点
custom_proxy_group=Bobby`select`[]美国节点`[]新加坡节点`[]香港节点`[]快速节点
custom_proxy_group=apiopenai`select`[]手动切换`[]美国节点`[]新加坡节点`[]香港节点`[]台湾节点`[]日本节点
custom_proxy_group=HoYoGames`select`[]DIRECT`[]手动切换`[]美国节点`[]新加坡节点`[]香港节点
custom_proxy_group=游戏平台`select`[]手动切换`[]美国节点`[]新加坡节点`[]香港节点`[]DIRECT
custom_proxy_group=漏网之鱼`select`[]手动切换`[]美国节点`[]新加坡节点`[]香港节点`[]DIRECT
custom_proxy_group=美国节点`select`(美国|🇺🇸|洛杉矶|(?i)\\bUS\\b|(?i)\\bUSA\\b|(?i)America|(?i)United[ _-]?States)
custom_proxy_group=香港节点`select`(香港|🇭🇰|(?i)\\bHK\\b|(?i)Hong[ _-]?Kong|(?i)\\bHKG\\b)
custom_proxy_group=新加坡节点`select`(新加坡|🇸🇬|狮城|(?i)\\bSG\\b|(?i)Singapore)
custom_proxy_group=日本节点`select`(日本|东京|大阪|🇯🇵|(?i)\\bJP\\b|(?i)Japan)
custom_proxy_group=台湾节点`select`(台湾|台北|新北|🇹🇼|(?i)\\bTW\\b|(?i)Taiwan)
custom_proxy_group=韩国节点`select`(韩国|首尔|🇰🇷|(?i)\\bKR\\b|(?i)Korea)
custom_proxy_group=加拿大节点`select`(加拿大|🇨🇦|(?i)Canada)
custom_proxy_group=印度节点`select`(印度|🇮🇳|(?i)India)
#custom_proxy_group=德国节点`select`(德|德国|(?i)German)
custom_proxy_group=俄罗斯节点`select`(俄罗斯|俄国|🇷🇺|(?i)Russia)
#custom_proxy_group=爱尔兰节点`select`(爱尔兰|(?i)Iran)
#custom_proxy_group=英国节点`select`(英|英国|(?i)England)
#custom_proxy_group=法国节点`select`(法|法国|(?i)France)
#custom_proxy_group=荷兰节点`select`(荷|荷兰|(?i)Netherland)
custom_proxy_group=快速节点`select`(虚通|BGP|IEPL|专线|优化|低延迟|高带宽|(?i)AnyPath)

enable_rule_generator=true
# overwrite_original_rules=true

clash_rule_base=https://raw.githubusercontent.com/pdlwf/router-rule/codex/fix-clash-config-template/Clash/GeneralConfig_OpenClash.yml
